export const accountConstants ={
    
    GET_ALL_VIRTUAL_SUCCESS : 'GET_ALL_VIRTUAL_SUCCESS',
    GET_ALL_VIRTUAL_PENDING : 'GET_ALL_VIRTUAL_PENDING',
    GET_ALL_VIRTUAL_FAILURE : 'GET_ALL_VIRTUAL_FAILURE',
    GET_ALL_VIRTUAL_RESET : 'GET_ALL_VIRTUAL_RESET',


    CREATE_NEW_VIRTUAL_SUCCESS : 'CREATE_NEW_VIRTUAL_SUCCESS',
    CREATE_NEW_VIRTUAL_PENDING : 'CREATE_NEW_VIRTUAL_PENDING',
    CREATE_NEW_VIRTUAL_FAILURE : 'CREATE_NEW_VIRTUAL_FAILURE',
    CREATE_NEW_VIRTUAL_RESET : 'CREATE_NEW_VIRTUAL_RESET',

    EDIT_VIRTUAL_SUCCESS : 'EDIT_VIRTUAL_SUCCESS',
    EDIT_VIRTUAL_PENDING : 'EDIT_VIRTUAL_PENDING',
    EDIT_VIRTUAL_FAILURE : 'EDIT_VIRTUAL_FAILURE',
    EDIT_VIRTUAL_RESET : 'EDIT_VIRTUAL_RESET',

    GET_VIRTUAL_ACCOUNT_TXT_SUCCESS : 'GET_VIRTUAL_ACCOUNT_TXT_SUCCESS',
    GET_VIRTUAL_ACCOUNT_TXT_PENDING : 'GET_VIRTUAL_ACCOUNT_TXT_PENDING',
    GET_VIRTUAL_ACCOUNT_TXT_FAILURE : 'GET_VIRTUAL_ACCOUNT_TXT_FAILURE',
    GET_VIRTUAL_ACCOUNT_TXT_RESET : 'GET_VIRTUAL_ACCOUNT_TXT_RESET',


    GET_ACC_BAL_SUCCESS : 'GET_ACC_BAL_SUCCESS',
    GET_ACC_BAL_PENDING : 'GET_ACC_BAL_PENDING',
    GET_ACC_BAL_FAILURE : 'GET_ACC_BAL_FAILURE',
    GET_ACC_BAL_RESET : 'GET_ACC_BAL_RESET',

    GET_ACC_HIST_SUCCESS : 'GET_ACC_HIST_SUCCESS',
    GET_ACC_HIST_PENDING : 'GET_ACC_HIST_PENDING',
    GET_ACC_HIST_FAILURE : 'GET_ACC_HIST_FAILURE',
    GET_ACC_HIST_RESET : 'GET_ACC_HIST_RESET',
        
}