

export const authConstants ={
    
    LOGIN_USER_SUCCESS : 'LOGIN_USER_SUCCESS',
    LOGIN_USER_PENDING : 'LOGIN_USER_PENDING',
    LOGIN_USER_FAILURE : 'LOGIN_USER_FAILURE',
    LOGIN_USER_RESET : 'LOGIN_USER_RESET',

    SIGNUP_SUCCESS : 'SIGNUP_SUCCESS',
    SIGNUP_PENDING : 'SIGNUP_PENDING',
    SIGNUP_FAILURE : 'SIGNUP_FAILURE',
    SIGNUP_RESET : 'SIGNUP_RESET',

    REFRESH_TOKEN_SUCCESS : 'REFRESH_TOKEN_SUCCESS',
    REFRESH_TOKEN_PENDING : 'REFRESH_TOKEN_PENDING',
    REFRESH_TOKEN_FAILURE : 'REFRESH_TOKEN_FAILURE',
    REFRESH_TOKEN_RESET : 'REFRESH_TOKEN_RESET',

    LOGOUT: 'USERS_LOGOUT',

    LOGOUT_USER_SUCCESS : 'LOGOUT_USER_SUCCESS',
    LOGOUT_USER_PENDING : 'LOGOUT_USER_PENDING',
    LOGOUT_USER_FAILURE : 'LOGOUT_USER_FAILURE',
    LOGOUT_USER_RESET :   'LOGOUT_USER__RESET',

    CHANGE_PASSWORD_SUCCESS : 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_PENDING : 'CHANGE_PASSWORD_PENDING',
    CHANGE_PASSWORD_FAILURE : 'CHANGE_PASSWORD_FAILURE',
    CHANGE_PASSWORD_RESET :   'CHANGE_PASSWORD__RESET',

    FORGOT_PASSWORD_SUCCESS : 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_PENDING : 'FORGOT_PASSWORD_PENDING',
    FORGOT_PASSWORD_FAILURE : 'FORGOT_PASSWORD_FAILURE',
    FORGOT_PASSWORD_RESET :   'FORGOT_PASSWORD_RESET',

    VALIDATE_PASSWORD_OTP_SUCCESS : 'VALIDATE_PASSWORD_OTP_SUCCESS',
    VALIDATE_PASSWORD_OTP_PENDING : 'VALIDATE_PASSWORD_OTP_PENDING',
    VALIDATE_PASSWORD_OTP_FAILURE : 'VALIDATE_PASSWORD_OTP_FAILURE',
    VALIDATE_PASSWORD_OTP_RESET :   'VALIDATE_PASSWORD_OTP_RESET',

    COMPLETE_PASSWORD_RESET_SUCCESS : 'COMPLETE_PASSWORD_RESET',
    COMPLETE_PASSWORD_RESET_PENDING : 'COMPLETE_PASSWORD_RESET',
    COMPLETE_PASSWORD_RESET_FAILURE : 'COMPLETE_PASSWORD_RESET',
    COMPLETE_PASSWORD_RESET_RESET :   'COMPLETE_PASSWORD_RESET',

    
}

