export const myBizUsers ={
    
    GET_ALL_MYUSERS_SUCCESS : 'GET_ALL_MYUSERS_SUCCESS',
    GET_ALL_MYUSERS_PENDING : 'GET_ALL_MYUSERS_PENDING',
    GET_ALL_MYUSERS_FAILURE : 'GET_ALL_MYUSERS_FAILURE',
    GET_ALL_MYUSERS_RESET : 'GET_ALL_MYUSERS_RESET',


    CREATE_NEW_USERS_SUCCESS : 'CREATE_NEW_USERS_SUCCESS',
    CREATE_NEW_USERS_PENDING : 'CREATE_NEW_USERS_PENDING',
    CREATE_NEW_USERS_FAILURE : 'CREATE_NEW_USERS_FAILURE',
    CREATE_NEW_USERS_RESET : 'CREATE_NEW_USERS_RESET',

    EDIT_USERS_SUCCESS : 'EDIT_USERS_SUCCESS',
    EDIT_USERS_PENDING : 'EDIT_USERS_PENDING',
    EDIT_USERS_FAILURE : 'EDIT_USERS_FAILURE',
    EDIT_USERS_RESET : 'EDIT_USERS_RESET',

    

    

    
}