export const myBizConstants ={
    
    GET_ALL_BIZ_SUCCESS : 'GET_ALL_BIZ_SUCCESS',
    GET_ALL_BIZ_PENDING : 'GET_ALL_BIZ_PENDING',
    GET_ALL_BIZ_FAILURE : 'GET_ALL_BIZ_FAILURE',
    GET_ALL_BIZ_RESET : 'GET_ALL_BIZ_RESET',

    ADD_NEW_BIZ_SUCCESS : 'ADD_NEW_BIZ_SUCCESS',
    ADD_NEW_BIZ_PENDING : 'ADD_NEW_BIZ_PENDING',
    ADD_NEW_BIZ_FAILURE : 'ADD_NEW_BIZ_FAILURE',
    ADD_NEW_BIZ_RESET : 'ADD_NEW_BIZ_RESET',

    GET_A_BIZ_DETAILS_SUCCESS : 'GET_A_BIZ_DETAILS_SUCCESS',
    GET_A_BIZ_DETAILS_PENDING : 'GET_A_BIZ_DETAILS_PENDING',
    GET_A_BIZ_DETAILS_FAILURE : 'GET_A_BIZ_DETAILS_FAILURE',
    GET_A_BIZ_DETAILS_RESET : 'GET_A_BIZ_DETAILS_RESET',

    APPROVE_A_BIZ_SUCCESS : 'APPROVE_A_BIZ_SUCCESS',
    APPROVE_A_BIZ_PENDING : 'APPROVE_A_BIZ_PENDING',
    APPROVE_A_BIZ_FAILURE : 'APPROVE_A_BIZ_FAILURE',
    APPROVE_A_BIZ_RESET : 'APPROVE_A_BIZ_RESET',

    ENABLE_BOBRDERLESS_FOR_BIZ_SUCCESS : 'ENABLE_BOBRDERLESS_FOR_BIZ_SUCCESS',
    ENABLE_BOBRDERLESS_FOR_BIZ_PENDING : 'ENABLE_BOBRDERLESS_FOR_BIZ_PENDING',
    ENABLE_BOBRDERLESS_FOR_BIZ_FAILURE : 'ENABLE_BOBRDERLESS_FOR_BIZ_FAILURE',
    ENABLE_BOBRDERLESS_FOR_BIZ_RESET : 'ENABLE_BOBRDERLESS_FOR_BIZ_RESET',

    

    
}